## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
## Name
## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
name: Next.js CI
## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
## Events ( Triggered on push in << feature/* >> branches and on pull requests in << pre-production >> branch )
## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
on:
  push:
    branches:
      - "feature/*"
      - "updates"
  pull_request:
    branches:
      - pre-production
## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
## Settings
## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
defaults:
  run:
    working-directory: ./source
## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
## Actions
## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      ## Step 1 - Checking repository
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      - name: Checking repository
        uses: actions/checkout@v4
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      ## Step 2 - Setting up NodeJS
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      - name: Setting up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22.7.0"
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      ## Step 3 - Restoring modules cache
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      - name: Restoring modules cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      ## Step 4 - Installing dependencies
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      - name: Installing dependencies
        run: npm install
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      ## Step 5 - Running tests
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      # - name: Running tests
      #   run: npm test
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      ## Step 6 - Restoring build cache
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      - name: Restoring build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: nextjs-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nextjs-build-
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      ## Step 7 - Building app
      ## ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ##
      - name: Building app
        run: npm run build